//
// AlertingConfigurationWithLastUpdated.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AlertingConfigurationWithLastUpdated: Codable { 


    public var id: String?
    public var alertName: String
    public var muteUntil: Int64?
    public var integrationIds: [String]
    public var eventFilteringConfiguration: EventFilteringConfiguration
    public var customPayload: String?
    public var lastUpdated: Int64?

    public init(id: String?, alertName: String, muteUntil: Int64?, integrationIds: [String], eventFilteringConfiguration: EventFilteringConfiguration, customPayload: String?, lastUpdated: Int64?) {
        self.id = id
        self.alertName = alertName
        self.muteUntil = muteUntil
        self.integrationIds = integrationIds
        self.eventFilteringConfiguration = eventFilteringConfiguration
        self.customPayload = customPayload
        self.lastUpdated = lastUpdated
    }

}
