//
// ApplicationItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ApplicationItem: Codable { 


    public var application: Application
    public var metrics: [String:[[Double]]]

    public init(application: Application, metrics: [String:[[Double]]]) {
        self.application = application
        self.metrics = metrics
    }

}
