//
// AuditLogResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AuditLogResponse: Codable { 


    public var total: Int64?
    public var entries: [AuditLogEntry]?

    public init(total: Int64?, entries: [AuditLogEntry]?) {
        self.total = total
        self.entries = entries
    }

}
