//
// BuiltInEventSpecification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct BuiltInEventSpecification: Codable { 


    public var id: String?
    public var shortPluginId: String?
    public var name: String?
    public var description: String?
    public var hyperParams: [HyperParam]
    public var ruleInputs: [RuleInput]
    public var severity: Int?
    public var triggering: Bool?
    public var enabled: Bool?

    public init(id: String?, shortPluginId: String?, name: String?, description: String?, hyperParams: [HyperParam], ruleInputs: [RuleInput], severity: Int?, triggering: Bool?, enabled: Bool?) {
        self.id = id
        self.shortPluginId = shortPluginId
        self.name = name
        self.description = description
        self.hyperParams = hyperParams
        self.ruleInputs = ruleInputs
        self.severity = severity
        self.triggering = triggering
        self.enabled = enabled
    }

}
