//
// ConfigVersion.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ConfigVersion: Codable { 


    public var id: String
    public var created: Int64?
    public var enabled: Bool?

    public init(id: String, created: Int64?, enabled: Bool?) {
        self.id = id
        self.created = created
        self.enabled = enabled
    }

}
