//
// Connection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Connection: Codable { 


    public var connectedSnapshotId: String?
    public var id: String?

    public init(connectedSnapshotId: String?, id: String?) {
        self.connectedSnapshotId = connectedSnapshotId
        self.id = id
    }

}
