//
// CustomEventSpecification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CustomEventSpecification: Codable { 


    public var id: String?
    public var name: String
    public var entityType: String
    public var query: String?
    public var triggering: Bool?
    public var description: String?
    public var expirationTime: Int64?
    public var enabled: Bool?
    public var rules: [AbstractRule]

    public init(id: String?, name: String, entityType: String, query: String?, triggering: Bool?, description: String?, expirationTime: Int64?, enabled: Bool?, rules: [AbstractRule]) {
        self.id = id
        self.name = name
        self.entityType = entityType
        self.query = query
        self.triggering = triggering
        self.description = description
        self.expirationTime = expirationTime
        self.enabled = enabled
        self.rules = rules
    }

}
