//
// EmailIntegration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct EmailIntegration: Codable { 


    public var emails: [String]
    public var id: String?
    public var kind: String
    public var name: String

    public init(emails: [String]id: String?, kind: String, name: String) {
        self.emails = emails
        self.id = id
        self.kind = kind
        self.name = name
    }

}
