//
// Endpoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Endpoint: Codable { 


    public enum ModelType: String, Codable {
        case undefined = "UNDEFINED"
        case rpc = "RPC"
        case event = "EVENT"
        case graphql = "GRAPHQL"
        case batch = "BATCH"
        case shell = "SHELL"
        case http = "HTTP"
        case sdk = "SDK"
        case _internal = "INTERNAL"
        case database = "DATABASE"
        case messaging = "MESSAGING"
        case page = "PAGE"
        case pageResource = "PAGE_RESOURCE"
    }
    public enum EntityType: String, Codable {
        case application = "APPLICATION"
        case service = "SERVICE"
        case endpoint = "ENDPOINT"
    }
    public var id: String?
    public var label: String?
    public var type: ModelType
    public var serviceId: String?
    public var technologies: [String]
    public var isSynthetic: Bool?
    public var synthetic: Bool?
    public var entityType: EntityType?

    public init(id: String?, label: String?, type: ModelType, serviceId: String?, technologies: [String], isSynthetic: Bool?, synthetic: Bool?, entityType: EntityType?) {
        self.id = id
        self.label = label
        self.type = type
        self.serviceId = serviceId
        self.technologies = technologies
        self.isSynthetic = isSynthetic
        self.synthetic = synthetic
        self.entityType = entityType
    }

}
