//
// EndpointItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct EndpointItem: Codable { 


    public var endpoint: Endpoint
    public var metrics: [String:[[Double]]]

    public init(endpoint: Endpoint, metrics: [String:[[Double]]]) {
        self.endpoint = endpoint
        self.metrics = metrics
    }

}
