//
// EventSpecificationInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct EventSpecificationInfo: Codable { 


    public enum ModelType: String, Codable, CaseIterable {
        case builtIn = "BUILT_IN"
        case custom = "CUSTOM"
    }
    public var id: String?
    public var name: String?
    public var description: String?
    public var entityType: String
    public var type: ModelType
    public var severity: Int?
    public var triggering: Bool?
    public var invalid: Bool?
    public var enabled: Bool?

    public init(id: String?, name: String?, description: String?, entityType: String, type: ModelType, severity: Int?, triggering: Bool?, invalid: Bool?, enabled: Bool?) {
        self.id = id
        self.name = name
        self.description = description
        self.entityType = entityType
        self.type = type
        self.severity = severity
        self.triggering = triggering
        self.invalid = invalid
        self.enabled = enabled
    }

}
