//
// GetCombinedMetrics.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct GetCombinedMetrics: Codable { 


    public var timeFrame: TimeFrame?
    public var plugin: String
    public var query: String?
    public var snapshotIds: [String]?
    public var rollup: Int?
    public var metrics: [String]

    public init(timeFrame: TimeFrame?, plugin: String, query: String?, snapshotIds: [String]?, rollup: Int?, metrics: [String]) {
        self.timeFrame = timeFrame
        self.plugin = plugin
        self.query = query
        self.snapshotIds = snapshotIds
        self.rollup = rollup
        self.metrics = metrics
    }

}
