//
// GetCallGroups.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct GetCallGroups: Codable { 


    public var pagination: CursorPagination?
    public var order: Order?
    public var timeFrame: TimeFrame?
    public var group: Group
    public var tagFilters: [TagFilter]?
    public var metrics: [MetricConfiguration]

    public init(pagination: CursorPagination?, order: Order?, timeFrame: TimeFrame?, group: Group, tagFilters: [TagFilter]?, metrics: [MetricConfiguration]) {
        self.pagination = pagination
        self.order = order
        self.timeFrame = timeFrame
        self.group = group
        self.tagFilters = tagFilters
        self.metrics = metrics
    }

}
