//
// GetWebsiteMetrics.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct GetWebsiteMetrics: Codable { 


    public enum ModelType: String, Codable {
        case pageload = "PAGELOAD"
        case resourceload = "RESOURCELOAD"
        case httprequest = "HTTPREQUEST"
        case error = "ERROR"
    }
    public var timeFrame: TimeFrame?
    public var metrics: [WebsiteMonitoringMetricsConfiguration]
    public var type: ModelType
    public var tagFilters: [TagFilter]?

    public init(timeFrame: TimeFrame?, metrics: [WebsiteMonitoringMetricsConfiguration], type: ModelType, tagFilters: [TagFilter]?) {
        self.timeFrame = timeFrame
        self.metrics = metrics
        self.type = type
        self.tagFilters = tagFilters
    }

}
