//
// GetWebsiteBeaconGroups.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct GetWebsiteBeaconGroups: Codable { 


    public enum ModelType: String, Codable, CaseIterable {
        case pageload = "PAGELOAD"
        case resourceload = "RESOURCELOAD"
        case httprequest = "HTTPREQUEST"
        case error = "ERROR"
    }
    public var pagination: CursorPagination?
    public var timeFrame: TimeFrame?
    public var group: WebsiteBeaconTagGroup
    public var order: Order?
    public var type: ModelType
    public var tagFilters: [TagFilter]?
    public var metrics: [WebsiteMonitoringMetricsConfiguration]

    public init(pagination: CursorPagination?, timeFrame: TimeFrame?, group: WebsiteBeaconTagGroup, order: Order?, type: ModelType, tagFilters: [TagFilter]?, metrics: [WebsiteMonitoringMetricsConfiguration]) {
        self.pagination = pagination
        self.timeFrame = timeFrame
        self.group = group
        self.order = order
        self.type = type
        self.tagFilters = tagFilters
        self.metrics = metrics
    }

}
