//
// GoogleChatIntegration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct GoogleChatIntegration: Codable { 


    public var webhookUrl: String
    public var id: String?
    public var kind: String
    public var name: String

    public init(webhookUrl: String, id: String?, kind: String, name: String) {
        self.webhookUrl = webhookUrl
        self.id = id
        self.kind = kind
        self.name = name
    }

}
