//
// HistoricBaseline.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct HistoricBaseline: Codable { 


    public enum Seasonality: String, Codable, CaseIterable {
        case weekly = "WEEKLY"
        case daily = "DAILY"
    }
    public enum Operator: String, Codable, CaseIterable {
        case gt = "GT"
        case gte = "GTE"
        case lt = "LT"
        case lte = "LTE"
    }
    public var seasonality: Seasonality
    public var baseline: [[Double]]
    public var deviationFactor: Double?
    public var type: String
    public var _operator: Operator
    public var lastUpdated: Int64?

    public init(seasonality: Seasonality, baseline: [[Double]], deviationFactor: Double?type: String, _operator: Operator, lastUpdated: Int64?) {
        self.seasonality = seasonality
        self.baseline = baseline
        self.deviationFactor = deviationFactor
        self.type = type
        self._operator = _operator
        self.lastUpdated = lastUpdated
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case seasonality
        case baseline
        case deviationFactor
        case type
        case _operator = "operator"
        case lastUpdated
    }

}
