//
// HttpPathSegmentMatchingRule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct HttpPathSegmentMatchingRule: Codable { 


    public enum ModelType: String, Codable, CaseIterable {
        case unsupported = "UNSUPPORTED"
        case fixed = "FIXED"
        case parameter = "PARAMETER"
        case matchAll = "MATCH_ALL"
    }
    public var type: ModelType

    public init(type: ModelType) {
        self.type = type
    }

}
