//
// HttpEndpointConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct HttpEndpointConfig: Codable { 


    public var serviceId: String?
    public var endpointNameByFirstPathSegmentRuleEnabled: Bool?
    public var endpointNameByCollectedPathTemplateRuleEnabled: Bool?
    public var rules: [HttpEndpointRule]

    public init(serviceId: String?, endpointNameByFirstPathSegmentRuleEnabled: Bool?, endpointNameByCollectedPathTemplateRuleEnabled: Bool?, rules: [HttpEndpointRule]) {
        self.serviceId = serviceId
        self.endpointNameByFirstPathSegmentRuleEnabled = endpointNameByFirstPathSegmentRuleEnabled
        self.endpointNameByCollectedPathTemplateRuleEnabled = endpointNameByCollectedPathTemplateRuleEnabled
        self.rules = rules
    }

}
