//
// HyperParam.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct HyperParam: Codable { 


    public enum ValueFormat: String, Codable, CaseIterable {
        case number = "NUMBER"
        case bytes = "BYTES"
        case percentage = "PERCENTAGE"
        case millis = "MILLIS"
        case seconds = "SECONDS"
        case micros = "MICROS"
        case rate = "RATE"
        case byteRate = "BYTE_RATE"
        case undefined = "UNDEFINED"
    }
    public var id: String?
    public var name: String?
    public var description: String?
    public var defaultValue: Double?
    public var minValue: Double?
    public var maxValue: Double?
    public var valueFormat: ValueFormat?

    public init(id: String?, name: String?, description: String?, defaultValue: Double?, minValue: Double?, maxValue: Double?, valueFormat: ValueFormat?) {
        self.id = id
        self.name = name
        self.description = description
        self.defaultValue = defaultValue
        self.minValue = minValue
        self.maxValue = maxValue
        self.valueFormat = valueFormat
    }

}
