//
// InfrastructureMetricResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InfrastructureMetricResult: Codable { 


    public var items: [MetricItem]?

    public init(items: [MetricItem]?) {
        self.items = items
    }

}
