//
// KubernetesPhysicalContext.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct KubernetesPhysicalContext: Codable { 


    public var pod: SnapshotPreview?
    public var namespace: SnapshotPreview?
    public var node: SnapshotPreview?
    public var cluster: SnapshotPreview?

    public init(pod: SnapshotPreview?, namespace: SnapshotPreview?, node: SnapshotPreview?, cluster: SnapshotPreview?) {
        self.pod = pod
        self.namespace = namespace
        self.node = node
        self.cluster = cluster
    }

}
