//
// LogEntryActor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct LogEntryActor: Codable { 


    public enum ModelType: String, Codable {
        case user = "USER"
        case apiToken = "API_TOKEN"
    }
    public var type: ModelType
    public var id: String?
    public var name: String?
    public var email: String?

    public init(type: ModelType, id: String?, name: String?, email: String?) {
        self.type = type
        self.id = id
        self.name = name
        self.email = email
    }

}
