//
// MaintenanceConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MaintenanceConfig: Codable { 


    public var id: String?
    public var name: String?
    public var query: String
    public var windows: [MaintenanceWindow]?

    public init(id: String?, name: String?, query: String, windows: [MaintenanceWindow]?) {
        self.id = id
        self.name = name
        self.query = query
        self.windows = windows
    }

}
