//
// MetricItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MetricItem: Codable { 


    public var snapshotId: String?
    public var plugin: String?
    public var from: Int64?
    public var to: Int64?
    public var tags: [String]?
    public var label: String?
    public var host: String?
    public var metrics: [String:[[Double]]]?

    public init(snapshotId: String?, plugin: String?, from: Int64?, to: Int64?, tags: [String]?, label: String?, host: String?, metrics: [String:[[Double]]]?) {
        self.snapshotId = snapshotId
        self.plugin = plugin
        self.from = from
        self.to = to
        self.tags = tags
        self.label = label
        self.host = host
        self.metrics = metrics
    }

}
