//
// MetricInstance.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MetricInstance: Codable { 


    public enum Formatter: String, Codable, CaseIterable {
        case number = "NUMBER"
        case bytes = "BYTES"
        case percentage = "PERCENTAGE"
        case millis = "MILLIS"
        case seconds = "SECONDS"
        case micros = "MICROS"
        case rate = "RATE"
        case byteRate = "BYTE_RATE"
        case undefined = "UNDEFINED"
    }
    public var formatter: Formatter
    public var label: String?
    public var description: String?
    public var metricId: String?
    public var pluginId: String?
    public var custom: Bool?

    public init(formatter: Formatter, label: String?, description: String?, metricId: String?, pluginId: String?, custom: Bool?) {
        self.formatter = formatter
        self.label = label
        self.description = description
        self.metricId = metricId
        self.pluginId = pluginId
        self.custom = custom
    }

}
