//
// MonitoringState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MonitoringState: Codable { 


    public var hostCount: Int?
    public var firstKnownReportingTime: Int64?

    public init(hostCount: Int?, firstKnownReportingTime: Int64?) {
        self.hostCount = hostCount
        self.firstKnownReportingTime = firstKnownReportingTime
    }

}
