//
// PagerdutyIntegration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PagerdutyIntegration: Codable { 


    public var serviceIntegrationKey: String
    public var id: String?
    public var kind: String
    public var name: String

    public init(serviceIntegrationKey: String, id: String?, kind: String, name: String) {
        self.serviceIntegrationKey = serviceIntegrationKey
        self.id = id
        self.kind = kind
        self.name = name
    }

}
