//
// PathParameterHttpPathSegmentMatchingRule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PathParameterHttpPathSegmentMatchingRule: Codable { 


    public enum ModelType: String, Codable {
        case unsupported = "UNSUPPORTED"
        case fixed = "FIXED"
        case parameter = "PARAMETER"
        case matchAll = "MATCH_ALL"
    }
    public var name: String?
    public var type: ModelType

    public init(name: String?type: ModelType) {
        self.name = name
        self.type = type
    }

}
