//
// PluginResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PluginResult: Codable { 


    public var plugin: String?
    public var label: String?

    public init(plugin: String?, label: String?) {
        self.plugin = plugin
        self.label = label
    }

}
