//
// PrometheusWebhookIntegration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PrometheusWebhookIntegration: Codable { 


    public var webhookUrl: String
    public var receiver: String?
    public var id: String?
    public var kind: String
    public var name: String

    public init(webhookUrl: String, receiver: String?, id: String?, kind: String, name: String) {
        self.webhookUrl = webhookUrl
        self.receiver = receiver
        self.id = id
        self.kind = kind
        self.name = name
    }

}
