//
// SearchFieldResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct SearchFieldResult: Codable { 


    public var keyword: String?
    public var description: String?
    public var context: String?
    public var termType: String?
    public var fixedValues: [String]?

    public init(keyword: String?, description: String?, context: String?, termType: String?, fixedValues: [String]?) {
        self.keyword = keyword
        self.description = description
        self.context = context
        self.termType = termType
        self.fixedValues = fixedValues
    }

}
