//
// ServiceItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ServiceItem: Codable { 


    public var service: Service
    public var metrics: [String:[[Double]]]

    public init(service: Service, metrics: [String:[[Double]]]) {
        self.service = service
        self.metrics = metrics
    }

}
