//
// SlownessWebsiteAlertRule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct SlownessWebsiteAlertRule: Codable { 


    public enum Aggregation: String, Codable {
        case sum = "SUM"
        case mean = "MEAN"
        case max = "MAX"
        case min = "MIN"
        case p25 = "P25"
        case p50 = "P50"
        case p75 = "P75"
        case p90 = "P90"
        case p95 = "P95"
        case p98 = "P98"
        case p99 = "P99"
        case distinctCount = "DISTINCT_COUNT"
    }
    public var aggregation: Aggregation
    public var alertType: String
    public var metricName: String

    public init(aggregation: AggregationalertType: String, metricName: String) {
        self.aggregation = aggregation
        self.alertType = alertType
        self.metricName = metricName
    }

}
