//
// SnapshotResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct SnapshotResult: Codable { 


    public var items: [SnapshotItem]?

    public init(items: [SnapshotItem]?) {
        self.items = items
    }

}
