//
// SoftwareVersion.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct SoftwareVersion: Codable { 


    public var name: String?
    public var version: String?
    public var origin: String
    public var type: String?
    public var usedBy: [SoftwareUser]

    public init(name: String?, version: String?, origin: String, type: String?, usedBy: [SoftwareUser]) {
        self.name = name
        self.version = version
        self.origin = origin
        self.type = type
        self.usedBy = usedBy
    }

}
