//
// SpanRelation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct SpanRelation: Codable { 


    public var applications: [Application]
    public var service: Service?
    public var endpoint: Endpoint?
    public var physicalContext: PhysicalContext?

    public init(applications: [Application], service: Service?, endpoint: Endpoint?, physicalContext: PhysicalContext?) {
        self.applications = applications
        self.service = service
        self.endpoint = endpoint
        self.physicalContext = physicalContext
    }

}
