//
// Span.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Span: Codable { 


    public enum Kind: String, Codable {
        case unknown = "UNKNOWN"
        case entry = "ENTRY"
        case exit = "EXIT"
        case intermediate = "INTERMEDIATE"
    }
    public var id: String?
    public var parentId: String?
    public var callId: String?
    public var name: String?
    public var label: String?
    public var start: Int64?
    public var duration: Int64?
    public var calculatedSelfTime: Int64?
    public var errorCount: Int?
    public var batchSize: Int?
    public var batchSelfTime: Int64?
    public var kind: Kind
    public var isSynthetic: Bool?
    public var data: [String:Any]
    public var source: SpanRelation?
    public var destination: SpanRelation?
    public var stackTrace: [StackTraceItem]
    public var childSpans: [Span]

    public init(id: String?, parentId: String?, callId: String?, name: String?, label: String?, start: Int64?, duration: Int64?, calculatedSelfTime: Int64?, errorCount: Int?, batchSize: Int?, batchSelfTime: Int64?, kind: Kind, isSynthetic: Bool?, data: [String:Any], source: SpanRelation?, destination: SpanRelation?, stackTrace: [StackTraceItem], childSpans: [Span]) {
        self.id = id
        self.parentId = parentId
        self.callId = callId
        self.name = name
        self.label = label
        self.start = start
        self.duration = duration
        self.calculatedSelfTime = calculatedSelfTime
        self.errorCount = errorCount
        self.batchSize = batchSize
        self.batchSelfTime = batchSelfTime
        self.kind = kind
        self.isSynthetic = isSynthetic
        self.data = data
        self.source = source
        self.destination = destination
        self.stackTrace = stackTrace
        self.childSpans = childSpans
    }

}
