//
// SplunkIntegration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct SplunkIntegration: Codable { 


    public var url: String
    public var token: String
    public var id: String?
    public var kind: String
    public var name: String

    public init(url: String, token: Stringid: String?, kind: String, name: String) {
        self.url = url
        self.token = token
        self.id = id
        self.kind = kind
        self.name = name
    }

}
