//
// StackTraceLine.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct StackTraceLine: Codable { 


    public var file: String?
    public var name: String?
    public var line: Int?
    public var column: Int?
    public var translationStatus: Int?
    public var translationExplanation: String?

    public init(file: String?, name: String?, line: Int?, column: Int?, translationStatus: Int?, translationExplanation: String?) {
        self.file = file
        self.name = name
        self.line = line
        self.column = column
        self.translationStatus = translationStatus
        self.translationExplanation = translationExplanation
    }

}
