//
// SyntheticCallRule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct SyntheticCallRule: Codable { 


    public var name: String?
    public var description: String?
    public var matchSpecification: Any
    public var enabled: Bool?

    public init(name: String?, description: String?, matchSpecification: Any, enabled: Bool?) {
        self.name = name
        self.description = description
        self.matchSpecification = matchSpecification
        self.enabled = enabled
    }

}
