//
// TagFilter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TagFilter: Codable { 


    public enum Operator: String, Codable {
        case equals = "EQUALS"
        case contains = "CONTAINS"
        case lessThan = "LESS_THAN"
        case lessOrEqualThan = "LESS_OR_EQUAL_THAN"
        case greaterThan = "GREATER_THAN"
        case greaterOrEqualThan = "GREATER_OR_EQUAL_THAN"
        case notEmpty = "NOT_EMPTY"
        case notEqual = "NOT_EQUAL"
        case notContain = "NOT_CONTAIN"
        case isEmpty = "IS_EMPTY"
        case notBlank = "NOT_BLANK"
        case isBlank = "IS_BLANK"
        case startsWith = "STARTS_WITH"
        case endsWith = "ENDS_WITH"
        case notStartsWith = "NOT_STARTS_WITH"
        case notEndsWith = "NOT_ENDS_WITH"
    }
    public enum Entity: String, Codable {
        case notApplicable = "NOT_APPLICABLE"
        case destination = "DESTINATION"
        case source = "SOURCE"
    }
    public var name: String?
    public var value: String
    public var _operator: Operator
    public var entity: Entity?

    public init(name: String?, value: String, _operator: Operator, entity: Entity?) {
        self.name = name
        self.value = value
        self._operator = _operator
        self.entity = entity
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case value
        case _operator = "operator"
        case entity
    }

}
