//
// TimeFrame.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TimeFrame: Codable { 


    public var windowSize: Int64?
    public var to: Int64?

    public init(windowSize: Int64?, to: Int64?) {
        self.windowSize = windowSize
        self.to = to
    }

}
