//
// Trace.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Trace: Codable { 


    public var id: String?
    public var label: String?
    public var startTime: Int64?
    public var duration: Int64?
    public var erroneous: Bool?
    public var service: Service?
    public var endpoint: Endpoint?

    public init(id: String?, label: String?, startTime: Int64?, duration: Int64?, erroneous: Bool?, service: Service?, endpoint: Endpoint?) {
        self.id = id
        self.label = label
        self.startTime = startTime
        self.duration = duration
        self.erroneous = erroneous
        self.service = service
        self.endpoint = endpoint
    }

}
