//
// TraceGroupsItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TraceGroupsItem: Codable { 


    public var name: String?
    public var timestamp: Int64?
    public var cursor: IngestionOffsetCursor
    public var metrics: [String:[[Double]]]

    public init(name: String?, timestamp: Int64?, cursor: IngestionOffsetCursor, metrics: [String:[[Double]]]) {
        self.name = name
        self.timestamp = timestamp
        self.cursor = cursor
        self.metrics = metrics
    }

}
