//
// TreeNodeResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TreeNodeResult: Codable { 


    public var tree: [TreeNode]?

    public init(tree: [TreeNode]?) {
        self.tree = tree
    }

}
