//
// TreeNode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TreeNode: Codable { 


    public var snapshotId: String?
    public var type: String?
    public var children: [TreeNode]?
    public var incomingConnection: [Connection]?
    public var outgoingConnection: [Connection]?

    public init(snapshotId: String?, type: String?, children: [TreeNode]?, incomingConnection: [Connection]?, outgoingConnection: [Connection]?) {
        self.snapshotId = snapshotId
        self.type = type
        self.children = children
        self.incomingConnection = incomingConnection
        self.outgoingConnection = outgoingConnection
    }

}
