//
// UnsupportedHttpPathSegmentMatchingRule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct UnsupportedHttpPathSegmentMatchingRule: Codable { 


    public enum ModelType: String, Codable, CaseIterable {
        case unsupported = "UNSUPPORTED"
        case fixed = "FIXED"
        case parameter = "PARAMETER"
        case matchAll = "MATCH_ALL"
    }
    public var unsupportedType: String?
    public var type: ModelType

    public init(unsupportedType: String?type: ModelType) {
        self.unsupportedType = unsupportedType
        self.type = type
    }

}
