//
// UsageResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct UsageResult: Codable { 


    public var time: Int64?
    public var items: [UsageResultItems]?

    public init(time: Int64?, items: [UsageResultItems]?) {
        self.time = time
        self.items = items
    }

}
