//
// ValidatedAlertingChannelInputInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ValidatedAlertingChannelInputInfo: Codable { 


    public enum EventTypes: String, Codable {
        case incident = "INCIDENT"
        case critical = "CRITICAL"
        case warning = "WARNING"
        case change = "CHANGE"
        case online = "ONLINE"
        case offline = "OFFLINE"
        case _none = "NONE"
    }
    public var id: String?
    public var label: String
    public var query: String?
    public var eventTypes: [EventTypes]?
    public var selectedEvents: Int?
    public var enabled: Bool?
    public var invalid: Bool?

    public init(id: String?, label: String, query: String?, eventTypes: [EventTypes]?, selectedEvents: Int?, enabled: Bool?, invalid: Bool?) {
        self.id = id
        self.label = label
        self.query = query
        self.eventTypes = eventTypes
        self.selectedEvents = selectedEvents
        self.enabled = enabled
        self.invalid = invalid
    }

}
