//
// WebhookIntegration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct WebhookIntegration: Codable { 


    public var webhookUrls: [String]
    public var headers: [String]?
    public var id: String?
    public var kind: String
    public var name: String

    public init(webhookUrls: [String], headers: [String]?, id: String?, kind: String, name: String) {
        self.webhookUrls = webhookUrls
        self.headers = headers
        self.id = id
        self.kind = kind
        self.name = name
    }

}
