//
// WebsiteAlertConfigWithMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct WebsiteAlertConfigWithMetadata: Codable { 


    public var name: String
    public var description: String?
    public var websiteId: String
    public var severity: Int?
    public var triggering: Bool?
    public var tagFilters: [TagFilter]
    public var rule: WebsiteAlertRule
    public var baseline: HistoricBaseline?
    public var alertChannelIds: [String]
    public var granularity: Int64?
    public var timeThreshold: WebsiteTimeThreshold
    public var id: String
    public var created: Int64?
    public var readOnly: Bool?
    public var enabled: Bool?
    public var threshold: Threshold

    public init(name: String, description: String?, websiteId: String, severity: Int?, triggering: Bool?, tagFilters: [TagFilter], rule: WebsiteAlertRule, baseline: HistoricBaseline?, alertChannelIds: [String], granularity: Int64?, timeThreshold: WebsiteTimeThreshold, id: String, created: Int64?, readOnly: Bool?, enabled: Bool?, threshold: Threshold) {
        self.name = name
        self.description = description
        self.websiteId = websiteId
        self.severity = severity
        self.triggering = triggering
        self.tagFilters = tagFilters
        self.rule = rule
        self.baseline = baseline
        self.alertChannelIds = alertChannelIds
        self.granularity = granularity
        self.timeThreshold = timeThreshold
        self.id = id
        self.created = created
        self.readOnly = readOnly
        self.enabled = enabled
        self.threshold = threshold
    }

}
