//
// WebsiteAlertRule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct WebsiteAlertRule: Codable { 


    public var alertType: String
    public var metricName: String

    public init(alertType: String, metricName: String) {
        self.alertType = alertType
        self.metricName = metricName
    }

}
