//
// WebsiteBeaconGroupsItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct WebsiteBeaconGroupsItem: Codable { 


    public var name: String?
    public var earliestTimestamp: Int64?
    public var cursor: IngestionOffsetCursor
    public var metrics: [String:[[Double]]]

    public init(name: String?, earliestTimestamp: Int64?, cursor: IngestionOffsetCursor, metrics: [String:[[Double]]]) {
        self.name = name
        self.earliestTimestamp = earliestTimestamp
        self.cursor = cursor
        self.metrics = metrics
    }

}
