//
// WebsiteMonitoringMetricDescription.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct WebsiteMonitoringMetricDescription: Codable { 


    public var metricId: String?
    public var label: String?
    public var formatter: String?
    public var description: String?
    public var aggregations: [String]?
    public var beaconTypes: [String]?

    public init(metricId: String?, label: String?, formatter: String?, description: String?, aggregations: [String]?, beaconTypes: [String]?) {
        self.metricId = metricId
        self.label = label
        self.formatter = formatter
        self.description = description
        self.aggregations = aggregations
        self.beaconTypes = beaconTypes
    }

}
