//
// WebsiteBeaconsItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct WebsiteBeaconsItem: Codable { 


    public var beacon: WebsiteMonitoringBeacon
    public var cursor: IngestionOffsetCursor

    public init(beacon: WebsiteMonitoringBeacon, cursor: IngestionOffsetCursor) {
        self.beacon = beacon
        self.cursor = cursor
    }

}
