//
// WebsiteMetricResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct WebsiteMetricResult: Codable { 


    public var empty: Bool?

    public init(empty: Bool?) {
        self.empty = empty
    }

}
