//
// AbstractIntegration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AbstractIntegration: Codable { 


    public var id: String?
    public var kind: String
    public var name: String

    public init(id: String?, kind: String, name: String) {
        self.id = id
        self.kind = kind
        self.name = name
    }

}
