//
// BeaconResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct BeaconResult: Codable { 


    public var items: [WebsiteBeaconsItem]
    public var canLoadMore: Bool?
    public var totalHits: Int?
    public var totalRepresentedItemCount: Int?

    public init(items: [WebsiteBeaconsItem], canLoadMore: Bool?, totalHits: Int?, totalRepresentedItemCount: Int?) {
        self.items = items
        self.canLoadMore = canLoadMore
        self.totalHits = totalHits
        self.totalRepresentedItemCount = totalRepresentedItemCount
    }

}
