//
// CloudfoundryPhysicalContext.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CloudfoundryPhysicalContext: Codable { 


    public var application: SnapshotPreview?
    public var space: SnapshotPreview?
    public var organization: SnapshotPreview?
    public var cfInstanceIndex: String?

    public init(application: SnapshotPreview?, space: SnapshotPreview?, organization: SnapshotPreview?, cfInstanceIndex: String?) {
        self.application = application
        self.space = space
        self.organization = organization
        self.cfInstanceIndex = cfInstanceIndex
    }

}
