//
// EndpointMetricResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct EndpointMetricResult: Codable { 


    public var items: [EndpointItem]
    public var page: Int?
    public var pageSize: Int?
    public var totalHits: Int?

    public init(items: [EndpointItem], page: Int?, pageSize: Int?, totalHits: Int?) {
        self.items = items
        self.page = page
        self.pageSize = pageSize
        self.totalHits = totalHits
    }

}
