//
// IngestionOffsetCursor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct IngestionOffsetCursor: Codable { 


    public var ingestionTime: Int64?
    public var offset: Int?

    public init(ingestionTime: Int64?, offset: Int?) {
        self.ingestionTime = ingestionTime
        self.offset = offset
    }

}
