//
// InstanaVersionInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InstanaVersionInfo: Codable { 


    public var branch: String?
    public var commit: String?
    public var imageTag: String?

    public init(branch: String?, commit: String?, imageTag: String?) {
        self.branch = branch
        self.commit = commit
        self.imageTag = imageTag
    }

}
