//
// MaintenanceWindow.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MaintenanceWindow: Codable { 


    public var id: String?
    public var start: Int64?
    public var end: Int64?

    public init(id: String?, start: Int64?, end: Int64?) {
        self.id = id
        self.start = start
        self.end = end
    }

}
