//
// PhysicalContext.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PhysicalContext: Codable { 


    public var process: SnapshotPreview?
    public var container: SnapshotPreview?
    public var host: SnapshotPreview?
    public var cluster: SnapshotPreview?
    public var cloudfoundry: CloudfoundryPhysicalContext?
    public var kubernetes: KubernetesPhysicalContext?

    public init(process: SnapshotPreview?, container: SnapshotPreview?, host: SnapshotPreview?, cluster: SnapshotPreview?, cloudfoundry: CloudfoundryPhysicalContext?, kubernetes: KubernetesPhysicalContext?) {
        self.process = process
        self.container = container
        self.host = host
        self.cluster = cluster
        self.cloudfoundry = cloudfoundry
        self.kubernetes = kubernetes
    }

}
