//
// ReleaseWithMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ReleaseWithMetadata: Codable { 


    public var name: String?
    public var start: Int64?
    public var id: String?
    public var lastUpdated: Int64?

    public init(name: String?, start: Int64?, id: String?, lastUpdated: Int64?) {
        self.name = name
        self.start = start
        self.id = id
        self.lastUpdated = lastUpdated
    }

}
