//
// Release.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Release: Codable { 


    public var name: String?
    public var start: Int64?

    public init(name: String?, start: Int64?) {
        self.name = name
        self.start = start
    }

}
