//
// RuleInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct RuleInput: Codable { 


    public enum InputKind: String, Codable {
        case metric = "METRIC"
        case snapshotField = "SNAPSHOT_FIELD"
        case event = "EVENT"
        case derivedMetric = "DERIVED_METRIC"
        case metricPattern = "METRIC_PATTERN"
    }
    public var inputKind: InputKind
    public var inputName: String?

    public init(inputKind: InputKind, inputName: String?) {
        self.inputKind = inputKind
        self.inputName = inputName
    }

}
