//
// ServiceConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ServiceConfig: Codable { 


    public var id: String?
    public var name: String?
    public var comment: String?
    public var label: String?
    public var enabled: Bool
    public var matchSpecification: [ServiceMatchingRule]

    public init(id: String?, name: String?, comment: String?, label: String?, enabled: Bool, matchSpecification: [ServiceMatchingRule]) {
        self.id = id
        self.name = name
        self.comment = comment
        self.label = label
        self.enabled = enabled
        self.matchSpecification = matchSpecification
    }

}
