//
// ServiceMatchingRule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ServiceMatchingRule: Codable { 


    public var key: String?
    public var value: String?

    public init(key: String?, value: String?) {
        self.key = key
        self.value = value
    }

}
