//
// SlackIntegration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct SlackIntegration: Codable { 


    public var webhookUrl: String
    public var iconUrl: String
    public var channel: String
    public var id: String?
    public var kind: String
    public var name: String

    public init(webhookUrl: String, iconUrl: String, channel: Stringid: String?, kind: String, name: String) {
        self.webhookUrl = webhookUrl
        self.iconUrl = iconUrl
        self.channel = channel
        self.id = id
        self.kind = kind
        self.name = name
    }

}
