//
// SnapshotPreview.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct SnapshotPreview: Codable { 


    public var id: String?
    public var time: Int64?
    public var label: String?
    public var plugin: String?
    public var data: [String:Any]?

    public init(id: String?, time: Int64?, label: String?, plugin: String?, data: [String:Any]?) {
        self.id = id
        self.time = time
        self.label = label
        self.plugin = plugin
        self.data = data
    }

}
