//
// SnapshotItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct SnapshotItem: Codable { 


    public var snapshotId: String?
    public var plugin: String?
    public var from: Int64?
    public var to: Int64?
    public var tags: [String]?
    public var label: String?
    public var host: String?

    public init(snapshotId: String?, plugin: String?, from: Int64?, to: Int64?, tags: [String]?, label: String?, host: String?) {
        self.snapshotId = snapshotId
        self.plugin = plugin
        self.from = from
        self.to = to
        self.tags = tags
        self.label = label
        self.host = host
    }

}
