//
// TraceItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TraceItem: Codable { 


    public var trace: Trace
    public var cursor: IngestionOffsetCursor

    public init(trace: Trace, cursor: IngestionOffsetCursor) {
        self.trace = trace
        self.cursor = cursor
    }

}
