//
// UsageResultItems.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct UsageResultItems: Codable { 


    public var name: String?
    public var sims: Int64?

    public init(name: String?, sims: Int64?) {
        self.name = name
        self.sims = sims
    }

}
