//
// UsersResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct UsersResult: Codable { 


    public var users: [UserResult]?

    public init(users: [UserResult]?) {
        self.users = users
    }

}
