//
// ValidatedMaintenanceConfigWithStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ValidatedMaintenanceConfigWithStatus: Codable { 


    public enum Status: String, Codable {
        case unscheduled = "UNSCHEDULED"
        case scheduled = "SCHEDULED"
        case active = "ACTIVE"
        case finished = "FINISHED"
    }
    public var id: String?
    public var name: String?
    public var query: String
    public var windows: [MaintenanceWindow]?
    public var lastUpdated: Int64?
    public var status: Status
    public var invalid: Bool?

    public init(id: String?, name: String?, query: String, windows: [MaintenanceWindow]?, lastUpdated: Int64?, status: Status, invalid: Bool?) {
        self.id = id
        self.name = name
        self.query = query
        self.windows = windows
        self.lastUpdated = lastUpdated
        self.status = status
        self.invalid = invalid
    }

}
