//
// Website.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Website: Codable { 


    public var id: String?
    public var appName: String?
    public var name: String?

    public init(id: String?, appName: String?, name: String?) {
        self.id = id
        self.appName = appName
        self.name = name
    }

}
