//
// EventsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



open class EventsAPI {
    /**
     Get Event
     
     - parameter eventId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getEvent(eventId: String, apiResponseQueue: DispatchQueue = InstanaClientAPI.apiResponseQueue, completion: @escaping ((_ data: EventResult?,_ error: Error?) -> Void)) {
        getEventWithRequestBuilder(eventId: eventId).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Event
     - GET /api/events/{eventId}
     - API Key:
       - type: apiKey authorization 
       - name: ApiKeyAuth
     - parameter eventId: (path)  
     - returns: RequestBuilder<EventResult> 
     */
    open class func getEventWithRequestBuilder(eventId: String) -> RequestBuilder<EventResult> {
        var path = "/api/events/{eventId}"
        let eventIdPreEscape = "\(APIHelper.mapValueToPathItem(eventId))"
        let eventIdPostEscape = eventIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{eventId}", with: eventIdPostEscape, options: .literal, range: nil)
        let URLString = InstanaClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<EventResult>.Type = InstanaClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get alerts
     
     - parameter windowSize: (query)  (optional)
     - parameter from: (query)  (optional)
     - parameter to: (query)  (optional)
     - parameter excludeTriggeredBefore: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getEvents(windowSize: Int64? = nil, from: Int64? = nil, to: Int64? = nil, excludeTriggeredBefore: Bool? = nil, apiResponseQueue: DispatchQueue = InstanaClientAPI.apiResponseQueue, completion: @escaping ((_ data: [EventResult]?,_ error: Error?) -> Void)) {
        getEventsWithRequestBuilder(windowSize: windowSize, from: from, to: to, excludeTriggeredBefore: excludeTriggeredBefore).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get alerts
     - GET /api/events
     - API Key:
       - type: apiKey authorization 
       - name: ApiKeyAuth
     - parameter windowSize: (query)  (optional)
     - parameter from: (query)  (optional)
     - parameter to: (query)  (optional)
     - parameter excludeTriggeredBefore: (query)  (optional)
     - returns: RequestBuilder<[EventResult]> 
     */
    open class func getEventsWithRequestBuilder(windowSize: Int64? = nil, from: Int64? = nil, to: Int64? = nil, excludeTriggeredBefore: Bool? = nil) -> RequestBuilder<[EventResult]> {
        let path = "/api/events"
        let URLString = InstanaClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "windowSize": windowSize?.encodeToJSON(), 
            "from": from?.encodeToJSON(), 
            "to": to?.encodeToJSON(), 
            "excludeTriggeredBefore": excludeTriggeredBefore?.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<[EventResult]>.Type = InstanaClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
